import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		int n = Integer.parseInt(args[0]);
		boolean isGirl = false;
		boolean isBoy = false;
		int two = 0;
		int three = 0;
		int four = 0;
		int children = 0;
		double avg = 0.0;
		for (int i = 1; i <= n; i++){
			while ((isBoy != true) || (isGirl != true)) {
				if (generator.nextDouble() < 0.5) {
					isGirl = true;
					children++;
				}
				else {
					isBoy = true;
					children++;
				}
		
			}
			avg = avg + children;
			if (children == 2){
				two++;
			}
			if (children == 3){
				three++;
			}
			if (children >= 4){
				four++;
			}
			isBoy = false;
			isGirl = false;
			children = 0;
		}
		avg = (avg/n);
		System.out.println("Average: " + avg + " children to get at least on of each gender.");
		System.out.println("Number of families with 2 children: " + two);
		System.out.println("Number of families with 3 children: " + three);
		System.out.println("Number of families with 4 or more children: " + four);
		if ((two >= three) && (two >= four)){
			System.out.println("The most common number of children is 2.");
		}
		if ((three > two) && (three >= four)) {
			System.out.println("The most common number of children is 3.");
		}
		if ((four > two) && (four > three)) {
			System.out.println("The most common number of children is 3.");
		}
	}
		
}

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
